steps:
  build:
    image: runmymind/docker-android-sdk:ubuntu-standalone
    commands:
      # install xvfb to allow for graphics-dependent tests
      - apt-get update && apt-get install -y --no-install-recommends xauth xvfb openjdk-11-jdk
      # install dotnet
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 8.0
      - export DOTNET_ROOT=$HOME/.dotnet
      - export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools
      # run cake
      - dotnet tool restore
      - xvfb-run -a dotnet cake --target Publish --branch $CI_COMMIT_BRANCH
    secrets:
      - nuget_key
      - baget_key
