steps:
  document:
    image: mcr.microsoft.com/dotnet/sdk:8.0-jammy
    commands:
      - dotnet tool restore
      - dotnet cake --target Document --branch $CI_COMMIT_BRANCH
  deploy:
    image: debian:latest
    when:
      - event: [push, manual]
        branch: release
    commands:
      - rm -rfv /var/www/MLEM/*
      - cp -rv Docs/_site/. /var/www/MLEM/
    volumes:
      - /var/www/MLEM:/var/www/MLEM
