on: pull_request
jobs:
  enforce-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: dangoslen/changelog-enforcer@v3
        with:
          changeLogPath: CHANGELOG.md
          missingUpdateErrorMessage: |
            The changelog was not updated. Please document your changes in Changelog.md.
            Run `git config core.hooksPath .githooks` to enable a git hook that ensures you updated the changelog before pushing.
